# Copyright © 2025 Brent Tunnicliff <brent@tunnicliff.dev>

name: Common Apple Pipeline

on:
  workflow_call:
    inputs:
      destination:
        description: "The destination used for xcodebuild commands"
        default: "macOS"
        required: true
        type: string
      scheme:
        description: "The scheme to use"
        required: true
        type: string
      skip_tests:
        description: "Should the tests be skipped"
        default: false
        required: false
        type: boolean
      workspace:
        description: "The workspace of the project"
        required: false
        type: string
      xcode_path:
        description: "The version of Xcode to use"
        default: "/Applications/Xcode_16.2.app"
        required: false
        type: string
jobs:
  pipeline:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Set Xcode version
        run: sudo xcode-select -s "${{ inputs.xcode_path }}"
      - name: Build Debug
        run: xcodebuild build
          ${{ inputs.workspace && -workspace "inputs.workspace" }}
          -scheme "${{ inputs.scheme }}"
          -destination "${{ inputs.destination }}"
          -configuration "Debug"
          -skipPackagePluginValidation
          CODE_SIGN_IDENTITY=""
          CODE_SIGNING_REQUIRED=NO
      - name: Build Unit tests
        if: ${{ ! inputs.skip_tests }}
        run: xcodebuild build-for-testing
          ${{ inputs.workspace && -workspace "inputs.workspace" }}
          -scheme "${{ inputs.scheme }}"
          -destination "${{ inputs.destination }}"
          -skipPackagePluginValidation
          CODE_SIGN_IDENTITY=""
          CODE_SIGNING_REQUIRED=NO
      - name: Run Unit tests
        if: ${{ ! inputs.skip_tests }}
        run: xcodebuild test-without-building
          ${{ inputs.workspace && -workspace "inputs.workspace" }}
          -scheme "${{ inputs.scheme }}"
          -destination "${{ inputs.destination }}"
          CODE_SIGN_IDENTITY=""
          CODE_SIGNING_REQUIRED=NO
      - name: Build Release
        run: xcodebuild build
          ${{ inputs.workspace && -workspace "inputs.workspace" }}
          -scheme "${{ inputs.scheme }}"
          -destination "${{ inputs.destination }}"
          -configuration "Release"
          -skipPackagePluginValidation
          CODE_SIGN_IDENTITY=""
          CODE_SIGNING_REQUIRED=NO
